theme: jekyll-theme-minimal
title: Dr. Karina Rojas
logo: '/images/paranal.jpg'
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: karygri
    github:  krojas
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

